version: '3.8'

services:
  # TSDB
  influxdb:
    image: influxdb:2.7-alpine
    container_name: coin-influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
      - ./influxdb_config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=coin # 조직 이름
      - DOCKER_INFLUXDB_INIT_BUCKET=market_data # 버킷 이름 (DB 명)
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    restart: always

  fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile.fastapi
    container_name: coin-fastapi
    environment:
      INFLUXDB_URL: ${INFLUXDB_URL}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./static_data:/app/static_data

  streamlit:
    build:
      context: .
      dockerfile: docker/Dockerfile.streamlit
    container_name: coin-streamlit
    environment:
      API_URL: ${API_URL}
    ports:
      - "8501:8501"
    restart: always

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    container_name: coin-worker
    environment:
      INFLUXDB_URL: ${INFLUXDB_URL}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
    depends_on:
      - influxdb
    restart: always
    volumes:
      - ./models:/app/models
      - ./static_data:/app/static_data

volumes:
